service: videoFileToS3

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  sendOTP:
    handler: index.add_file
    events:
      - http:
          path: /api/v1/uploadFile
          method: post
          cors: true
          
plugins:
  - serverless-offline          

